#!/bin/sh

EXEC=/usr/local/bin/redis-sentinel
PIDFILE=/var/run/redis-sentinel.pid
CONF="/etc/redis/sentinel.conf"

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
            echo "$PIDFILE exists, process is already running or crashed"
        else
            echo "Starting Redis sentinel..."
            $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
            echo "$PIDFILE does not exist, process is not running"
        else
            PID=$(cat $PIDFILE)
            echo "Stopping Redis sentinel..."
            kill $PID
            while [ -x /proc/${PID} ]
            do  
                echo "Waiting for Redis sentinel to shutdown ..."
                sleep 1
            done
            echo "Redis sentinel stopped"
        fi
        ;;
    status)
        PID=$(cat $PIDFILE)
        if [ ! -x /proc/${PID} ]
        then
            echo 'Redis sentinel is not running'
        else
            echo "Redis sentinel is running ($PID)"
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)  
        echo "Please use start, stop, restart or status as first argument"
        ;;
esac

